### ISSUE TITLE
Pyrus doesn't work through http proxy

### ISSUE THREAD

**Issue by olofa** [pyrus/Pyrus#79] opened 2011-12-07 13:37 UTC
Hi,

I'm using php 5.3.2 and pyrus 2.0.0a3. I have also tried with php 5.3.8.

I did:

pyrus set http_proxy fqdn:port

I run tcpdump on the http proxy server and this is what I get when trying to install a package:

GET /rest/p/pear2_net_transmitter/info.xml HTTP/1.0
Host: pear2.php.net
User-Agent: PEAR2_Pyrus/2.0.0a3/PHP/5.3.2
Accept:

Our squid3 proxy doesn't accept that. It wants to have it like this:

GET http://pear2.php.net/rest/p/pear2_net_transmitter/info.xml HTTP/1.0
Host: pear2.php.net
User-Agent: PEAR2_Pyrus/2.0.0a3/PHP/5.3.2
Accept:

I believe this is a bug in pyrus.

**Comment by saltybeagle** [comment] 2012-02-19 03:07
Should be fixed now. Thanks your help tacking down the bug

**Closed as completed** 2012-02-19 03:08 UTC

**Comment by kemitix** [comment] 2014-07-30 09:47
Hi, 

I'm getting this problem with the 2.0.0a4 release.

```
GET /rest/p/pyrus_developer/info.xml HTTP/1.0
Host: pyrus.net
User-Agent: Pyrus/2.0.0a4/PHP/5.5.9-1ubuntu4.3
Accept: 
Connection: close
```

**Comment by kemitix** [comment] 2014-07-30 11:08
Further digging I've found that, although the problem is fixed with PEAR2_HTTP_Request-0.3.1, Pyrus is still bundled with 0.3.0. The github repo for PEAR2_HTTP_Request has no 0.3.1 tag, but its master branch does include the fix we need for this issue.

Pull request 138 adds the correct version of PEAR2_HTTP_Request.
