### ISSUE TITLE
php folder copy is forbidden on Windows

### ISSUE THREAD

**Issue by error500** [pyrus/Pyrus#44] opened 2011-07-08 04:54 UTC
On an install command, after downloading, pyrus trys to make a copy of /php folder. Command is aborted on my pc
(Vista, i'm admin, i'm usin wamp with php 5.3.5)

Downloading pear.php.net/XML_Util=======================================>                            ] 71% ( 2/ 3 kb)
Connected...
Mime-type: application/octet-stream

PHP Warning:  rename(C:\wamp21\bin\php\php5.3.5,C:\wamp21\bin\php.old-php5.3.5): Le processus ne peut pas accÚder au fi
chier car ce fichier est utilisÚ par un autre processus. (code: 32) in phar://C:/wamp21/bin/php/php5.3.5/pyrus.phar/PEAR
2_Pyrus-2.0.0a3/php/PEAR2/Pyrus/AtomicFileTransaction/Transaction/TwoStage.php on line 82
PHP Stack trace:
PHP   1. {main}() C:\wamp21\bin\php\php5.3.5\pyrus.phar:0
PHP   2. PEAR2\Pyrus\ScriptFrontend\Commands->run() C:\wamp21\bin\php\php5.3.5\pyrus.phar:52
PHP   3. PEAR2\Pyrus\ScriptFrontend\Commands->install() phar://C:/wamp21/bin/php/php5.3.5/pyrus.phar/PEAR2_Pyrus-2.0.0a3
/php/PEAR2/Pyrus/ScriptFrontend/Commands.php:284
PHP   4. PEAR2\Pyrus\Installer::commit() phar://C:/wamp21/bin/php/php5.3.5/pyrus.phar/PEAR2_Pyrus-2.0.0a3/php/PEAR2/Pyru
s/ScriptFrontend/Commands.php:491
PHP   5. PEAR2\Pyrus\AtomicFileTransaction::commit() phar://C:/wamp21/bin/php/php5.3.5/pyrus.phar/PEAR2_Pyrus-2.0.0a3/ph
p/PEAR2/Pyrus/Installer.php:329
PHP   6. PEAR2\Pyrus\AtomicFileTransaction\Manager->commit() phar://C:/wamp21/bin/php/php5.3.5/pyrus.phar/PEAR2_Pyrus-2.
0.0a3/php/PEAR2/Pyrus/AtomicFileTransaction.php:91
PHP   7. PEAR2\Pyrus\AtomicFileTransaction\Transaction\TwoStage->commit() phar://C:/wamp21/bin/php/php5.3.5/pyrus.phar/P
EAR2_Pyrus-2.0.0a3/php/PEAR2/Pyrus/AtomicFileTransaction/Manager.php:165
PHP   8. rename() phar://C:/wamp21/bin/php/php5.3.5/pyrus.phar/PEAR2_Pyrus-2.0.0a3/php/PEAR2/Pyrus/AtomicFileTransaction
/Transaction/TwoStage.php:82

Warning: rename(C:\wamp21\bin\php\php5.3.5,C:\wamp21\bin\php.old-php5.3.5): Le processus ne peut pas accÚder au fichier
 car ce fichier est utilisÚ par un autre processus. (code: 32) in phar://C:/wamp21/bin/php/php5.3.5/pyrus.phar/PEAR2_Pyr
us-2.0.0a3/php/PEAR2/Pyrus/AtomicFileTransaction/Transaction/TwoStage.php on line 82

Call Stack:
    0.1370    1508104   1. {main}() C:\wamp21\bin\php\php5.3.5\pyrus.phar:0
    0.2222    3130352   2. PEAR2\Pyrus\ScriptFrontend\Commands->run() C:\wamp21\bin\php\php5.3.5\pyrus.phar:52
    0.3953    5662400   3. PEAR2\Pyrus\ScriptFrontend\Commands->install() phar://C:/wamp21/bin/php/php5.3.5/pyrus.phar/P
EAR2_Pyrus-2.0.0a3/php/PEAR2/Pyrus/ScriptFrontend/Commands.php:284
    0.4562    7040216   4. PEAR2\Pyrus\Installer::commit() phar://C:/wamp21/bin/php/php5.3.5/pyrus.phar/PEAR2_Pyrus-2.0.
0a3/php/PEAR2/Pyrus/ScriptFrontend/Commands.php:491
   51.6199   18095216   5. PEAR2\Pyrus\AtomicFileTransaction::commit() phar://C:/wamp21/bin/php/php5.3.5/pyrus.phar/PEAR
2_Pyrus-2.0.0a3/php/PEAR2/Pyrus/Installer.php:329
   51.6199   18095216   6. PEAR2\Pyrus\AtomicFileTransaction\Manager->commit() phar://C:/wamp21/bin/php/php5.3.5/pyrus.p
har/PEAR2_Pyrus-2.0.0a3/php/PEAR2/Pyrus/AtomicFileTransaction.php:91
   51.7005   18095048   7. PEAR2\Pyrus\AtomicFileTransaction\Transaction\TwoStage->commit() phar://C:/wamp21/bin/php/php
5.3.5/pyrus.phar/PEAR2_Pyrus-2.0.0a3/php/PEAR2/Pyrus/AtomicFileTransaction/Manager.php:165
   51.7015   18095080   8. rename() phar://C:/wamp21/bin/php/php5.3.5/pyrus.phar/PEAR2_Pyrus-2.0.0a3/php/PEAR2/Pyrus/Ato
micFileTransaction/Transaction/TwoStage.php:82

PEAR2\Pyrus\Installer\Exception: Installation failed
 PEAR2\Pyrus\AtomicFileTransaction\MultiException: ERROR: commit failed
  PEAR2\Pyrus\IOException: CRITICAL - unable to complete transaction, rename of actual to backup path failed
   PEAR2\Pyrus\AtomicFileTransaction\RuntimeException: Cannot rollback - not in a transaction

here with a handmade copy of /php to /.old_php ...

Downloading pear.php.net/XML_Util=======================================>                            ] 71% ( 2/ 3 kb)
Connected...
Mime-type: application/octet-stream

PEAR2\Pyrus\Installer\Exception: Installation failed==========================================>      ] 93% (16/17 kb)
 PEAR2\Pyrus\AtomicFileTransaction\MultiException: Unable to begin transaction
  PEAR2\Pyrus\AtomicFileTransaction\RuntimeException: Cannot begin - a backup directory still exists
   PEAR2\Pyrus\AtomicFileTransaction\RuntimeException: Cannot rollback - not in a transaction

**Comment by saltybeagle** [comment] 2011-07-08 11:51
This is a duplicate of https://github.com/pear2/PEAR2_Pyrus/issues/3

**Closed as completed by saltybeagle** 2011-07-08 11:51 UTC
