### ISSUE TITLE
installing mime_type fails: Unable to begin transaction

### ISSUE THREAD

**Issue by cweiske** [pyrus/Pyrus#15] opened 2011-05-30 06:56 UTC
```
$ /opt/phpfarm/inst/bin/php-5.3.6 pyrus.phar . install pear/mime_type
Pyrus version 2.0.0a3 SHA-1: BE7EA9D171AE3873F1BBAF692EEE9165BB14BD5D
Using PEAR installation found at /home/christian.weiske/pytest
Downloading pear.php.net/MIME_Type

Connected...
Mime-type: application/octet-stream

Downloading pear.php.net/PEAR==============================================================>         ] 90% (10/11 kb)
Connected...
Mime-type: application/octet-stream

Downloading pear.php.net/Archive_Tar================================================================>] 99% (287/288 kb)
Connected...
Mime-type: application/octet-stream

Downloading pear.php.net/Structures_Graph=====================================================>      ] 93% (16/17 kb)
Connected...
Mime-type: application/octet-stream

Downloading pear.php.net/Console_Getopt==========================================================>   ] 96% (28/29 kb)
Downloading pear.php.net/XML_Util
Connected...
Mime-type: application/octet-stream

PEAR2\Pyrus\Installer\Exception: Installation failed==========================================>      ] 93% (16/17 kb)
 PEAR2\Pyrus\AtomicFileTransaction\MultiException: Unable to begin transaction
  PEAR2\Pyrus\IOException: unrecoverable transaction error: cannot create journal path /opt/phpfarm/src/../inst/php-5.3.6/.journal-bin
   PEAR2\Pyrus\AtomicFileTransaction\RuntimeException: Cannot rollback - not in a transaction
```

**Comment by fpoirotte** [comment] 2011-07-21 21:48
This looks like a duplicate of bug #9. Could you make sure you have write access on your bin_dir?

**Comment by till** [comment] 2012-11-05 23:32
Duplicate.

**Closed as completed by till** 2012-11-05 23:32 UTC
Labels: bug
