### ISSUE TITLE
build xdebug: undefined property

### ISSUE THREAD

**Issue by cweiske** [pyrus/Pyrus#31] opened 2011-06-07 13:13 UTC
root@elysium: ~/xdebug> /opt/phpfarm/inst/bin/pyrus-5.3.6 build pecl/xdebug
Pyrus version 2.0.0a1 SHA-1: 2FDFB5E00A6D707437DBC047AAF9D115C6484D90
Using PEAR installation found at /opt/phpfarm/inst/php-5.3.6/pear
Building PECL extensions
PHP Notice:  Undefined property: pear2\Pyrus\PECLBuild::$current_callback in phar:///opt/phpfarm/inst/php-5.3.6/pyrus.phar/PEAR2_Pyrus-2.0.0a1/php/pear2/Pyrus/PECLBuild.php on line 470

Notice: Undefined property: pear2\Pyrus\PECLBuild::$current_callback in phar:///opt/phpfarm/inst/php-5.3.6/pyrus.phar/PEAR2_Pyrus-2.0.0a1/php/pear2/Pyrus/PECLBuild.php on line 470
WARNING: php_bin /opt/phpfarm/inst/php-5.3.6/bin/php appears to have a suffix farm/inst/php-5.3.6/bin/php, but config variable php_suffix does not match

**Comment by helgi** [comment] 2011-06-07 14:48
This is a duplicate of #19 - Please read over existing tickets, specially ones you reported yourself :-)

**Closed as completed by helgi** 2011-06-07 14:48 UTC
