### ISSUE TITLE
Pyrus: Installation of pecl/APC fails: constraint failed

### ISSUE THREAD

**Issue by cweiske** [pyrus/Pyrus#17] opened 2011-06-03 14:42 UTC
```
# ../inst/bin/pyrus-5.3.3 install pecl/apc
Pyrus version 2.0.0a2 SHA-1: CA3946A5C2C7DE7CD6ED89CAC7CCC06606E006D3
Using PEAR installation found at /opt/phpfarm/inst/php-5.3.3/pear
Downloading pecl.php.net/APC

Connected...
Mime-type: application/octet-stream

PEAR2\Pyrus\Registry\Exception: Error: package pecl.php.net/APC could not be installed in registry: Unable to execute statement: constraint failed
 Exception: Unable to execute statement: constraint failed
```

**Comment by cweiske** [comment] 2012-09-12 07:08
Still happens with

> Pyrus version 2.0.0a4 SHA-1: 72271D92C3AA1FA96DF9606CD538868544609A52

on php 5.4.6

**Comment by till** [comment] 2012-11-06 00:23
Duplicate of #60

**Closed as completed by till** 2012-11-06 00:23 UTC
Labels: bug
